kind: Service
apiVersion: v1
metadata:
  name: postgresql
  namespace: pers-zubkov
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
      labels:
        app: postgres-sql-test
